# Generated by Django 3.1.1 on 2020-09-10 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('membership_type', models.CharField(choices=[('super_membership', 'Super'), ('pro_membership', 'Pro'), ('free_membership', 'Free')], default='free_membership', max_length=40)),
                ('price', models.PositiveIntegerField(default=27)),
                ('stripe_plan_id', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SuperUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('stripe_customer_id', models.CharField(blank=True, max_length=60, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=10)),
                ('course_list', models.TextField(blank=True, null=True)),
                ('website_url', models.CharField(blank=True, max_length=100, null=True)),
                ('tweeter_url', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_url', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube_url', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='_base_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default='logo.png', upload_to='tutors/%Y%m%d/')),
                ('title', models.CharField(max_length=120)),
                ('bio', models.TextField()),
                ('study', models.CharField(choices=[('prof1', 'prof1'), ('prof2', 'prof2'), ('prof3', 'prof3')], default='prof1', max_length=30)),
                ('superuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='_superuser_tutor', to='memberships.superuser')),
            ],
        ),
        migrations.CreateModel(
            name='TutorMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='memberships.membership')),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='_tutor', to='memberships.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=60)),
                ('active', models.BooleanField(default=True)),
                ('tutor_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberships.tutormembership')),
            ],
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default='logo.png', upload_to='learners/%Y%m%d/')),
                ('superuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='_superuser_learner', to='memberships.superuser')),
            ],
        ),
    ]
