# Generated by Django 3.1.1 on 2020-09-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superuser',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
