# Generated by Django 3.1.1 on 2020-09-10 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_auto_20200910_2008'),
        ('courses', '0003_auto_20200910_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking',
            name='super_user',
        ),
        migrations.AddField(
            model_name='tracking',
            name='learner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='memberships.learner'),
            preserve_default=False,
        ),
    ]
